import '../styles/global.scss';

export const metadata = {
  title: "Econverse",
  description: "Generated by create next app",
  icons: {
    icon: "/LogoEconverse.svg",
  },
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
